# This workflow builds and tests a C/C++ project on Windows and Ubuntu
# using different compilers.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # The job will run on the operating system specified in the matrix
    runs-on: ${{ matrix.os }}

    strategy:
      # Ensures that all jobs in the matrix are attempted, even if one fails
      fail-fast: false
      matrix:
        # Defines the different configurations to run the job with
        include:
          - os: windows-latest
            build_type: Release
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            build_type: Release
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            build_type: Release
            c_compiler: clang
            cpp_compiler: clang++

    steps:
      # Step 1: Check out the repository's code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up a reusable variable for the build directory path
      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      # Step 3: Configure the CMake project
      # This step generates the build files for the specific platform and compiler
      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      # Step 4: Build the project using CMake
      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      # Step 5: Run the tests using CTest
      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ matrix.build_type }}

      # Step 6a: Run Windows executables
      # This step only runs on Windows runners
      - name: Run Windows Executables
        if: runner.os == 'Windows'
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        shell: bash
        run: |
          for exe in w_priority_inheritence w_priority_fault; do
            executable_name="${{ matrix.build_type }}/${exe}.exe"
            if [ -f "${executable_name}" ]; then
              echo "---"
              echo "Running ./${executable_name}"
              "./${executable_name}"
              echo "---"
            else
              echo "Error: Executable not found: $(pwd)/${executable_name}"
              exit 1
            fi
          done

      # Step 6b: Run Linux executables
      # This step only runs on Linux runners
      - name: Run Linux Executables
        if: runner.os == 'Linux'
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        shell: bash
        run: |
          for exe in l_priority_inheritence l_priority_fault; do
            executable_name="${exe}"
            if [ -f "${executable_name}" ]; then
              echo "---"
              echo "Running ./${executable_name}"
              "./${executable_name}"
              echo "---"
            else
              echo "Error: Executable not found: $(pwd)/${executable_name}"
              exit 1
            fi
          done
